spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/autoreview?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true

  profiles:
    include: auth

  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret: 5eb6bba091453cf2c2afb293c813f01aa198e617215c322191b8ad0ee21dbe98
  accessTokenExpireTime: 1800000 # 1000 * 60 * 30 = 30분
  refreshTokenExpireTime: 21600000 # 1000 * 60 * 60 * 6 = 6시간